# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1/install
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.1/install
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.1/install

matrix:
  include:
    - env: BUILD_TYPE=Debug
      os: osx
      osx_image: xcode8
      compiler: clang
    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode8
      compiler: clang
    - env: CLANG_VERSION=3.9 BUILD_TYPE=Debug
      os: linux
      addons: &clang39
        apt:
          packages:
            - clang-3.9
            - llvm-3.9-dev
            - g++-5
            - libedit-dev
            - zlibc
            - zlib1g 
            - zlib1g-dev
            - python3-dev
            - libopenblas-dev
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
    - env: CLANG_VERSION=3.9 BUILD_TYPE=Release
      os: linux
      addons: *clang39
    - env: GCC_VERSION=5 BUILD_TYPE=Debug
      os: linux
      addons: &gcc5
        apt:
          packages:
          - g++-5
          - llvm-3.9-dev
          - libedit-dev
          - zlibc
          - zlib1g 
          - zlib1g-dev
          - python3-dev
          - libopenblas-dev
          sources: *sources
    - env: GCC_VERSION=5 BUILD_TYPE=Release
      os: linux
      addons: *gcc5
    - env: GCC_VERSION=6 BUILD_TYPE=Debug
      os: linux
      addons: &gcc6
        apt:
          packages:
          - g++-6
          - llvm-3.9-dev
          - libedit-dev
          - zlibc
          - zlib1g 
          - zlib1g-dev
          - python3-dev
          - libopenblas-dev
          sources: *sources
    - env: GCC_VERSION=6 BUILD_TYPE=Release
      os: linux
      addons: *gcc6

install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
  - JOBS=2
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}" && cd "${DEPS_DIR}"

  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
       if [[ -z "$(ls -A ${DEPS_DIR}/cmake/bin)" ]]; then
         CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
         mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
       fi
      export PATH="${DEPS_DIR}/cmake/bin:${PATH}"
    else
      brew update
      if ! brew ls --version cmake &>/dev/null; then brew install cmake; fi
      brew install llvm@3.9 --with-clang
      brew install homebrew/science/openblas
      brew install python3
    fi
  ############################################################################
  # [linux]: Install the right version of libc++
  ############################################################################
  - |
    if [[ -n "$CLANG_VERSION" && "${TRAVIS_OS_NAME}" == "linux" && "${STDLIB}" != "libstdc++" ]]; then
        echo ""
    fi
before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - cmake . -Bbuild -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build build -- -j$JOBS

script:
  - cd build
  - ctest --output-on-failure -j$JOBS

notifications:
  email: false
